services:
    - type: web
      name: realtime-room-api
      env: docker
      plan: free
      dockerfilePath: docker/Dockerfile.api
      dockerContext: .
      healthCheckPath: /health
      envVars:
          - key: PORT
            value: 3000
          - key: CORS_ORIGIN
            value: "*"

    - type: web
      name: realtime-room-web
      env: docker
      plan: free
      dockerfilePath: docker/Dockerfile.web
      dockerContext: .
      envVars:
          # URL publique de l’API Render, à mettre après le 1er deploy de l’API
          - key: API_URL
            value: "CHANGE_ME_AFTER_DEPLOY"
