services:
    - type: web
      name: realtime-room-api
      env: docker
      plan: free
      dockerfilePath: docker/Dockerfile.api
      dockerContext: .
      healthCheckPath: /api
      envVars:
          - key: PORT
            value: 3000
          - key: CORS_ORIGIN
            value: "*"

    - type: web
      name: realtime-room-web
      env: docker
      plan: free
      dockerfilePath: docker/Dockerfile.web
      dockerContext: .
      envVars:
          - key: API_URL
            value: "CHANGE_ME_AFTER_DEPLOY"
